ci: add tests on all python versions on main

diff --git a/.github/workflows/xtc-tests.yml b/.github/workflows/xtc-tests.yml
--- a/.github/workflows/xtc-tests.yml
+++ b/.github/workflows/xtc-tests.yml
@@ -9,13 +9,14 @@ on:
 
 jobs:
   build:
+    if: github.event_name != 'pull_request'
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
         os: [ubuntu-latest, macos-14, macos-15]
-        python-version: ["3.12"]
-    steps:
+        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
+    steps: &build-steps
       - name: Checkout XTC Repository
         uses: actions/checkout@v5
         with:
@@ -23,9 +24,9 @@ jobs:
       - name: Ensure PR has linear history
         if: github.event_name == 'pull_request'
         run: |
-          MERGE_COMMITS="$(git rev-list --merges "$GITHUB_SHA^1..$GITHUB_SHA^2")"
-          if [ -n "$MERGE_COMMITS" ]; then
-            echo "::error::PR contains merges, always use rebase for updating branches: Merge commits: $MERGE_COMMITS" >&2
+          MERGE_COMMITS="$(git rev-list --merges "${GITHUB_SHA}^1..${GITHUB_SHA}^2")"
+          if [ -n "${MERGE_COMMITS}" ]; then
+            echo "::error::PR contains merges, always use rebase for updating branches: Merge commits: ${MERGE_COMMITS}" >&2
             exit 1
           fi
       - name: Install Linux Packages
@@ -37,7 +38,7 @@ jobs:
         if: runner.os == 'macOs'
         run: |
           brew install libomp x86_64-linux-gnu-binutils aarch64-elf-binutils
-          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:$DYLD_LIBRARY_PATH"
+          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:${DYLD_LIBRARY_PATH}"
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
         with:
@@ -58,7 +59,7 @@ jobs:
           pip install -r macos_tvm_requirements.txt
       - name: Dump Environment information
         run: |
-          python -c "import sys; print(sys.version)"
+          python -c 'import sys; print(sys.version)'
           pip list
           env | sort
       - name: Run Checks
@@ -95,3 +96,13 @@ jobs:
           name: py${{ matrix.python-version }}-${{ matrix.os }}
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: true
+
+  pr-build:
+    if: github.event_name == 'pull_request'
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, macos-15]
+        python-version: ["3.12"]
+    steps: *build-steps
